config_metadata: 'Saving time : 12/07/2023, 22:59:45'
name: 'get_pos_lstm_2'
save_experiment: true

# data options
data:
    path: 'data'
    language: 'French'
    sequence_length: 10
    pad: '<PAD>'
    unk: '<UNK>'
    sequence_function: 'dummy'
    indexes: [1, 3, 5]
    vocab:
        path: 'dictionary'
        unk_rate: 0.01
        save: false
        num_words: 33992

# task options
task:
    task_name: 'get_pos'
    get_pos_info:
        num_classes: 19
    get_morphy_info:
        num_classes: 28
        num_features: 13

# model options
model:
    model_name: 'lstm'
    lstm:
        lstm_hidd_size_1: 64
        lstm_hidd_size_2: null
        fc_hidd_size: []
        embedding_size: 64
        bidirectional: true
        activation: 'relu'
    bert:
        hidd_size: 100
        pretrained_model_name: 'bert-base-uncased'

# learning options
learning:
    loss: 'crossentropy'
    optimizer: 'adam'
    learning_rate: 0.01
    milesstone: [5, 15]
    gamma: 0.1
    epochs: 30
    batch_size: 2048
    shuffle: true
    drop_last: true
    save_checkpoint: true
